DROP TABLE IF EXISTS roster CASCADE;

CREATE TABLE roster(
      id SERIAL PRIMARY KEY,
      player_id INT NOT NULL,
      firstname VARCHAR(255) NOT NULL,
      lastname VARCHAR(255) NOT NULL,
      photo_url VARCHAR,
      age INT,
      height VARCHAR(255),
      weight VARCHAR(255),
      nationality VARCHAR,
      injured BOOLEAN,
      position VARCHAR,
      rating DECIMAL,
      appearences INT,
      lineups INT,
      minutes INT,
      total_goals INT,
      conceded_goals INT,
      assists INT,
      saves INT,
      total_passes INT,
      key_passes INT,
      accuracy_passes INT,
      total_tackles INT,
      total_blocks INT, 
      total_interceptions INT,
      total_duels INT,
      won_duels INT,
      attempted_dribbles INT,
      success_dribbles INT,
      drawn_fouls INT,
      committed_fouls INT,
      yellow_cards INT,
      yellowred_cards INT,
      red_cards INT,
      won_penalties INT,
      commited_penalties INT,
      scored_penalties INT, 
      missed_penalties INT,
      saved_penalties INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );