DROP TABLE IF EXISTS roster CASCADE;

CREATE TABLE roster(
      id SERIAL PRIMARY KEY,
      player_id INT NOT NULL,
      firstname VARCHAR(255) NOT NULL,
      lastname VARCHAR(255) NOT NULL,
      photo_url VARCHAR,
      age INT DEFAULT 0,
      height VARCHAR(255),
      weight VARCHAR(255),
      nationality VARCHAR,
      injured BOOLEAN,
      position VARCHAR,
      rating DECIMAL DEFAULT 0,
      appearences INT DEFAULT 0,
      lineups INT DEFAULT 0,
      minutes INT DEFAULT 0,
      total_goals INT DEFAULT 0,
      conceded_goals INT DEFAULT 0,
      assists INT DEFAULT 0,
      saves INT DEFAULT 0,
      total_passes INT DEFAULT 0,
      key_passes INT DEFAULT 0,
      accuracy_passes INT DEFAULT 0,
      total_tackles INT DEFAULT 0,
      total_blocks INT DEFAULT 0, 
      total_interceptions INT DEFAULT 0,
      total_duels INT DEFAULT 0,
      won_duels INT DEFAULT 0,
      attempted_dribbles INT DEFAULT 0,
      success_dribbles INT DEFAULT 0,
      drawn_fouls INT DEFAULT 0,
      committed_fouls INT DEFAULT 0,
      yellow_cards INT DEFAULT 0,
      yellowred_cards INT DEFAULT 0,
      red_cards INT DEFAULT 0,
      won_penalties INT DEFAULT 0,
      commited_penalties INT DEFAULT 0,
      scored_penalties INT DEFAULT 0, 
      missed_penalties INT DEFAULT 0,
      saved_penalties INT DEFAULT 0,
      user_id INT REFERENCES users(id) NOT NULL,
      match_day INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );